name: Backup Key Counts

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every day at 23:00 (11:00 PM UTC)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Commit and push key_counts.json
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add key_counts.json
        git commit -m "Backup key counts"
        git push
